global:
  scrape_interval: 5s # By default, scrape targets every 15 seconds.
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'seismographd'
    scrape_interval: 1s
    static_configs:
      - targets: ['0.0.0.0:10500']